service: projeto3

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  profile: automacao-curso
  region: us-east-1
  stage: prod

  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - ce:GetCostAndUsage
          Resource: '*'

functions:
  get_cost:
    handler: handler.get_cost
    events:
      - schedule: 
          rate: rate(1 minute)
          enabled: false
          input: {}
      - schedule: 
          rate: cron(0 12 ? * 1 *)
          enabled: true
          input: {}

plugins:
  - serverless-python-requirements

package: 
  patterns:
    - '!env'
    - '!node_modules'
    - '!*.json'
